### ISSUE TITLE
Missing album art and other features in Mixcloud

### ISSUE THREAD

**Issue by Invictaz** [jaryn-kubik/aimp_youtubedl#6] opened 2020-05-22 01:49 UTC
Hi @jaryn-kubik 

- Is it possible to fast forward in longer tracks (1 hour) to skip for example 20 minutes? Now it's only possible to fast forward a few minutes. It only plays what the buffer has downloaded.

- There is no album art downloaded from Mixcloud which would make this a killer feature in some skins

- When the playlist from Mixcloud is loaded only the urls are loaded but not parsed. Only when you click to play them.

**Comment by kubik-jaroslav** [comment] 2020-06-15 20:58
(1) Try AIMPYoutubeDL 1.0.5 and clear the "youtube-dl --format" field in options, after hiting save it should reset to a new default value, which should prefer streams that allow seeking anywhere, seems to work better on mixcloud.

(2) Duplicate of #4, unfortunately setting album art doesn't seem to work in aimp_dotnet at all from what I tried, so this is kinda impossible for now. When native exports in .net 5 come out I might revisit this and get rid of aimp_dotnet completely, so maybe someday.

(3) This is partially by design. Youtube-dl has the option to load full info about the whole playlist, but that means it opens each playlist item and loads it separately, which is really slow and can take minutes to complete, so users would probably just assume the app is frozen.

I am using the other option, which only loads what it can on the playlist page without loading anything else so you only get partial info. On mixcloud for some reason it just returns urls without track names even though they're there on the page, on youtube it returns both urls and track names.

This is something that needs to be solved on youtube-dl side, nothing i can do on my end, so you could potentially try creating and issue in the youtube-dl repo.

**Closed as completed by kubik-jaroslav** 2020-06-15 20:58 UTC

**Comment by kubik-jaroslav** [comment] 2020-07-17 20:03
Album Art added in v2.0.0
